version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: MongoDB.Driver
    versions:
    - 2.11.6
    - 2.12.0
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
  - dependency-name: EntityChange
    versions:
    - 4.1.0.98
  - dependency-name: Unity
    versions:
    - 5.11.10
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
