version: 7.0.0.{build}
os: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: 3ryD5hf/SIjWrc5NR5vg4I/thEV63YQU4hHJDPo0R/0Q+cA4+9o9BEjQ+tGvuYU0

init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - dotnet tool install --global coveralls.net

build_script:
  - dotnet pack KickStart.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test KickStart.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*"

after_test:
  - csmacnz.coveralls --useRelativePaths --multiple --input "opencover=test\KickStart.Autofac.Tests\coverage.opencover.xml;opencover=test\KickStart.AutoMapper.Tests\coverage.opencover.xml;opencover=test\KickStart.DependencyInjection.Tests\coverage.opencover.xml;opencover=test\KickStart.EntityChange.Tests\coverage.opencover.xml;opencover=test\KickStart.MongoDB.Tests\coverage.opencover.xml;opencover=test\KickStart.Ninject.Tests\coverage.opencover.xml;opencover=test\KickStart.SimpleInjector.Tests\coverage.opencover.xml;opencover=test\KickStart.Tests\coverage.opencover.xml;opencover=test\KickStart.Unity.Tests\coverage.opencover.xml;"

artifacts:
- path: artifacts\*.nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet