site_name: KickStart
theme: readthedocs
repo_url: https://github.com/loresoft/KickStart

pages:
- Home: index.md

- Configuration: configuration.md
- Usage: usage.md

- Startup Task: startup.md
- AutoMapper: automapper.md
- MongoDB: mongoDB.md

- Dependency Injection:
    - Generic Registration: di/registration.md
    - Autofac: di/autofac.md
    - DependencyInjection: di/dependencyInjection.md
    - Ninject: di/ninject.md
    - SimpleInjector: di/simpleInjector.md
    - Unity: di/unity.md

- Database Deployment:
    - Usage: db/database.md
    - Sql Server: db/sqlServer.md
    - PostgreSQL: db/postgreSQL.md
    - MySql: db/mySql.md
    - Sqlite: db/sqlite.md
    - MongoDB: db/mongoDB.md